services:
  webapp:
    build:
      context: ./frontend
    ports:
      - 3001:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build:
      context: ./webapp
    ports:
      - 3000:3000
    volumes:
      - ./webapp:/app
      - /app/node_modules